### ISSUE TITLE
Final evaluation calendar

### ISSUE THREAD

**Issue by pmhsfelix** [isel-leic-ls/1819-2-common#2]
This issue tracks changes to the final evaluation calendar, published here:
- [Final Evaluation calendar, teacher: Pedro Félix](https://github.com/isel-leic-ls/1819-2-common/wiki/final_eval_pf)
- [Final Evaluation calendar, teacher: Filipe Freitas](https://github.com/isel-leic-ls/1819-2-common/wiki/final_eval_ff)

**Comment by pmhsfelix** [comment]
The guide for the final evaluation is available here: [https://github.com/isel-leic-ls/1819-2-common/wiki/final_evaluation_guide](https://github.com/isel-leic-ls/1819-2-common/wiki/final_evaluation_guide)

**Comment by pmhsfelix** [comment]
There is a new slot available on Friday June 21, between 09:00 and 10:00

**Comment by fbfreitas** [comment]
There are new slots available in Final Evaluation calendar, teacher: Filipe Freitas

**Comment by fbfreitas** [comment]
There is a new slot available on July 18, between 09:00 and 10:00

**Comment by fbfreitas** [comment]
The Final Evaluation calendar of LI41N is avaliable in [final_LI41N](https://github.com/isel-leic-ls/1819-2-common/wiki/final_LI41N).

**Comment by fbfreitas** [comment]
There is a new slot available on thursday July 11, between 11:00 and 12:00, teacher: Pedro Felix
